-- V1: initial schema for the URL shortener.
-- Links are immutable after creation; clicks are an append-only child table,
-- so recording analytics never updates (or locks) a link row.

CREATE TABLE links (
    code          VARCHAR(32)                 NOT NULL PRIMARY KEY,
    target_url    VARCHAR(2048)               NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at    TIMESTAMP(6) WITH TIME ZONE,
    custom_alias  BOOLEAN                     NOT NULL
);

CREATE TABLE clicks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(32)                 NOT NULL REFERENCES links (code),
    clicked_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    referrer      VARCHAR(255)                NOT NULL,
    visitor_hash  VARCHAR(64)                 NOT NULL
);

CREATE INDEX idx_clicks_code_time ON clicks (code, clicked_at);

CREATE TABLE idempotency_keys (
    idem_key      VARCHAR(128)                NOT NULL PRIMARY KEY,
    request_hash  VARCHAR(64)                 NOT NULL,
    code          VARCHAR(32)                 NOT NULL REFERENCES links (code),
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
